// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmlxkpfwtcrlgkiuwyqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttbHhrcGZ3dGNybGdraXV3eXFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMDA4MTUsImV4cCI6MjA2NDU3NjgxNX0.iWd-WcLp4X9cdxhDTMT-eFzJotwD9wVI5wmLp9lJbTM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);